parameters:
- name: succeed
  displayName: Succeed or fail
  type: boolean
  default: false

trigger:
- main

strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

jobs:
- job: BuildAndTest
  pool:
    vmImage: windows-latest
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'Run pytest'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: "JaCoCo"
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
      failIfCoverageEmpty: true

  - script: |
      if [ $(succeed) = false ]; then
        echo "Failing the pipeline as per the succeed parameter."
        exit 1
      fi
    displayName: 'Conditional fail step'

- job: ErrorHandler
  dependsOn: BuildAndTest
  condition: failed()
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        az boards work-item create \
          --title "Build $(Build.BuildNumber) failed" \
          --type bug \
          --org $(System.TeamFoundationCollectionUri) \
          --project $(System.TeamProject)
    env: 
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
    displayName: 'Create work item on failure'
